# Generated by Django 3.2.20 on 2023-06-11 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=100)),
                ('principal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='college_principal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.college')),
                ('hod', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_hod', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_type', models.CharField(choices=[('HOD', 'Head Of Department'), ('Principal', 'Principal'), ('Staff', 'Staff')], max_length=40)),
                ('sid', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('profile_image', models.ImageField(default='/default.png', upload_to='profile_images')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.department')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(max_length=10)),
                ('reason', models.CharField(max_length=300)),
                ('leave_start_date', models.DateField()),
                ('leave_end_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20)),
                ('num_of_days', models.IntegerField()),
                ('previous_leaves', models.IntegerField()),
                ('pdf_file', models.FileField(upload_to='leave_letters/')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_hod', models.BooleanField(default=False)),
                ('approved_principal', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.leaveinfo')),
            ],
        ),
    ]
