# Generated by Django 3.2.20 on 2023-06-11 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(max_length=10)),
                ('reason', models.CharField(max_length=300)),
                ('leave_start_date', models.DateField()),
                ('leave_end_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20)),
                ('num_of_days', models.IntegerField()),
                ('previous_leaves', models.IntegerField()),
                ('pdf_file', models.FileField(upload_to='leave_letters/')),
            ],
        ),
        migrations.CreateModel(
            name='StaffDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_type', models.CharField(choices=[('HOD', 'Head Of Department'), ('Principal', 'Principal'), ('Staff', 'Staff')], max_length=40)),
                ('sid', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('profile_image', models.ImageField(default='/default.png', upload_to='profile_images')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.department')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='leaveinfo',
            name='applicant',
        ),
        migrations.DeleteModel(
            name='StaffProfile',
        ),
        migrations.AddField(
            model_name='leavedata',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.staffdetails'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.leavedata'),
        ),
        migrations.DeleteModel(
            name='LeaveInfo',
        ),
    ]
